name: Build

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git curl jq

      # Clone PenguinMod
      - name: Clone PenguinMod GUI
        run: |
          git clone --depth=1 https://github.com/PenguinMod/penguinmod.github.io.git
          cd penguinmod.github.io
          bun i --force

      - name: Clone PenguinMod VM
        run: |
          cd penguinmod.github.io
          git clone --depth=1 https://github.com/PenguinMod/PenguinMod-Vm.git
          cd PenguinMod-Vm
          bun i --force
          cd ..
          rm -rf node_modules/scratch-vm
          mv PenguinMod-Vm node_modules/scratch-vm

      - name: Clone PenguinMod Blocks
        run: |
          cd penguinmod.github.io
          git clone --depth=1 -b develop-builds https://github.com/PenguinMod/PenguinMod-Blocks.git
          cd PenguinMod-Blocks
          bun i --force
          cd ..
          rm -rf node_modules/scratch-blocks
          mv PenguinMod-Blocks node_modules/scratch-blocks

      - name: Clone PenguinMod Renderer
        run: |
          cd penguinmod.github.io
          git clone --depth=1 https://github.com/PenguinMod/PenguinMod-Render.git
          cd PenguinMod-Render
          bun i --force
          cd ..
          rm -rf node_modules/scratch-render
          mv PenguinMod-Render node_modules/scratch-render

      - name: Clone PenguinMod Paint
        run: |
          cd penguinmod.github.io
          git clone --depth=1 https://github.com/PenguinMod/PenguinMod-Paint.git
          cd PenguinMod-Paint
          bun i --force
          cd ..
          rm -rf node_modules/scratch-paint
          mv PenguinMod-Paint node_modules/scratch-paint

      # Build PenguinMod
      - name: Build PenguinMod
        run: |
          cd penguinmod.github.io
          bun run build
          cp -R build ../app
          cp package.json ../app/

      # Install Electron deps
      - name: Install Electron dependencies
        run: npm install # using npm instead of bun is important here!

      # Build Desktop App
      - name: Build Electron App
        run: npx electron-builder --linux AppImage deb rpm --win nsis --publish never

      - name: Upload builds
        uses: actions/upload-artifact@v4
        with:
          name: penguinmod-desktop-builds
          path: builds